// Built-in task templates — each template creates multiple sub-tasks automatically
export const TASK_TEMPLATES = [
  {
    id: 'daily_wird',
    icon: '🕌',
    title_ar: 'الورد اليومي',
    title_en: 'Daily Wird',
    color: '#0B5B50',
    tasks: [
      { title_ar: 'صلاة الفجر', title_en: 'Fajr prayer', priority: 'high', due_time: '05:00' },
      { title_ar: 'أذكار الصباح', title_en: 'Morning Dhikr', priority: 'high', due_time: '06:00' },
      { title_ar: 'قراءة صفحات القرآن', title_en: 'Quran reading', priority: 'medium', due_time: '07:00' },
      { title_ar: 'صلاة الظهر', title_en: 'Dhuhr prayer', priority: 'high', due_time: '12:30' },
      { title_ar: 'صلاة العصر', title_en: 'Asr prayer', priority: 'high', due_time: '15:30' },
      { title_ar: 'صلاة المغرب', title_en: 'Maghrib prayer', priority: 'high', due_time: '18:00' },
      { title_ar: 'أذكار المساء', title_en: 'Evening Dhikr', priority: 'medium', due_time: '18:30' },
      { title_ar: 'صلاة العشاء', title_en: 'Isha prayer', priority: 'high', due_time: '20:00' },
    ],
  },
  {
    id: 'morning_routine',
    icon: '🌅',
    title_ar: 'الروتين الصباحي',
    title_en: 'Morning Routine',
    color: '#B89A5E',
    tasks: [
      { title_ar: 'الاستيقاظ المبكر', title_en: 'Wake up early', priority: 'high', due_time: '05:30' },
      { title_ar: 'شرب الماء', title_en: 'Drink water', priority: 'medium', due_time: '05:35' },
      { title_ar: 'ممارسة الرياضة', title_en: 'Exercise', priority: 'medium', due_time: '06:00' },
      { title_ar: 'مراجعة أهداف اليوم', title_en: 'Review daily goals', priority: 'high', due_time: '07:00' },
      { title_ar: 'وجبة الإفطار', title_en: 'Breakfast', priority: 'medium', due_time: '07:30' },
    ],
  },
  {
    id: 'weekly_review',
    icon: '📊',
    title_ar: 'المراجعة الأسبوعية',
    title_en: 'Weekly Review',
    color: '#12897A',
    tasks: [
      { title_ar: 'مراجعة المهام المكتملة', title_en: 'Review completed tasks', priority: 'high' },
      { title_ar: 'تقييم الأهداف الأسبوعية', title_en: 'Evaluate weekly goals', priority: 'high' },
      { title_ar: 'تحديث ميزانية الأسبوع', title_en: 'Update weekly budget', priority: 'medium' },
      { title_ar: 'تخطيط الأسبوع القادم', title_en: 'Plan next week', priority: 'high' },
      { title_ar: 'مراجعة المشاريع العملية', title_en: 'Review work projects', priority: 'medium' },
    ],
  },
  {
    id: 'healthy_day',
    icon: '💪',
    title_ar: 'يوم صحي متكامل',
    title_en: 'Healthy Day',
    color: '#27AE60',
    tasks: [
      { title_ar: 'رياضة الصباح (30 دقيقة)', title_en: 'Morning workout (30 min)', priority: 'high', due_time: '06:30' },
      { title_ar: 'تناول وجبة إفطار صحية', title_en: 'Healthy breakfast', priority: 'medium', due_time: '08:00' },
      { title_ar: 'شرب 8 أكواب ماء', title_en: 'Drink 8 glasses of water', priority: 'medium' },
      { title_ar: 'المشي 10000 خطوة', title_en: 'Walk 10,000 steps', priority: 'medium' },
      { title_ar: 'وجبة غداء خفيفة', title_en: 'Light lunch', priority: 'medium', due_time: '13:00' },
      { title_ar: 'النوم المبكر', title_en: 'Early sleep', priority: 'medium', due_time: '22:00' },
    ],
  },
  {
    id: 'deep_work',
    icon: '🎯',
    title_ar: 'جلسة تركيز عميق',
    title_en: 'Deep Work Session',
    color: '#0B5B50',
    tasks: [
      { title_ar: 'تحديد هدف الجلسة', title_en: 'Define session goal', priority: 'high' },
      { title_ar: 'إغلاق الإشعارات', title_en: 'Disable notifications', priority: 'high' },
      { title_ar: 'بلوك تركيز (90 دقيقة)', title_en: 'Focus block (90 min)', priority: 'high' },
      { title_ar: 'استراحة قصيرة (15 دقيقة)', title_en: 'Short break (15 min)', priority: 'low' },
      { title_ar: 'مراجعة ما أُنجز', title_en: 'Review what was done', priority: 'medium' },
    ],
  },
  {
    id: 'learning_session',
    icon: '📚',
    title_ar: 'جلسة تعلّم',
    title_en: 'Learning Session',
    color: '#B89A5E',
    tasks: [
      { title_ar: 'مراجعة الدرس السابق', title_en: 'Review previous lesson', priority: 'medium' },
      { title_ar: 'قراءة/مشاهدة الدرس الجديد', title_en: 'Study new lesson', priority: 'high' },
      { title_ar: 'تدوين ملاحظات مهمة', title_en: 'Take notes', priority: 'high' },
      { title_ar: 'تطبيق عملي أو تمرين', title_en: 'Practice exercise', priority: 'medium' },
      { title_ar: 'مراجعة الملاحظات', title_en: 'Review notes', priority: 'low' },
    ],
  },
];